include: package:lints/recommended.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
linter:
  rules:
    unnecessary_parenthesis: true
    prefer_const_constructors: true
    prefer_final_locals: true