targets:
  $default:
    builders:
      dart_json_mapper:
        options:
          iterables: List, Set
        generate_for:
          - test/unit/_test.dart
      reflectable_builder:
        generate_for:
          - no/files