targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - test/unit/_test.dart
        options:
          compiler: dart2js
          dart2js_args:
            - --no-minify
      dart_json_mapper:
        options:
          iterables: List, Set
        generate_for:
          - test/unit/_test.dart
      reflectable:
        generate_for:
          - no/files